package com.video.avd.ads

enum class ScreenName {
    BACK_MUSIC_SHOWN,
    BACK_VIDEO_SHOWN,
    SINGLE_PLAYLIST_SHOWN,
    PLAYLIST_SHOWN,
    YOUTUBE_PLAYLIST_SHOWN,
    STATUS_HOME_SHOW,
    STATUS_VID_SHOW,
    HOME_FRAGMENT_SHOWN,
    VIDEO_ITEM_SHOWN,
    HOME_THEME_SHOWN,
    BACK_PLAYER_SHOWN,
    TOOLS_FRAGMENT_SHOWN,
    STREAM_FRAGMENT_SHOWN,
    AUDIO_CONVERTER_SHOWN,
    CLEANUP_FRAGMENT_SHOWN,
    YOUTUBE_HOME_SHOWN,
    VAULT_VIDEO_SHOWN,
    ALBUM_FRAGMENT_SHOWN,
    CREATE_PIN_SHOWN,
    PLAYER_SHOWN,
    TRIMMER_SHOWN,
    PRIVATE_SHOWN,
    DOWNLOADER_SHOWN,
    EXIT_SHOWN,
    SPLASH_SHOWN,
    NetworkStream,
    language,
    Cleaner,
    Theme,
    Storage,
    OBFULL1,
    OBFULL2
    }


